const INVALID_PROPS = [
  'p',
  'pt',
  'pb',
  'pl',
  'pr',
  'pv',
  'ph',
  'm',
  'mt',
  'mb',
  'ml',
  'mr',
  'mv',
  'mh',
  'width',
  'minWidth',
  'maxWidth',
  'height',
  'minHeight',
  'maxHeight',
  'color',
  'bgColor',
  'fontWeight',
  'textAlign',
  'textDecoration',
  'letterSpacing',
  'bold',
  'border',
  'borderRadius',
  'borderWidth',
  'bt',
  'bb',
  'br',
  'bl',
  'inline',
  'level',
  'password',
  'bgImage',
  'vertical',
  'hstart',
  'hcenter',
  'hend',
  'vstart',
  'vcenter',
  'vend',
  'center',
  'between',
  'around',
  'full',
  'overflow',
  'color',
  'keepWord',
];

export const removeNonHTMLProps = (
  props: { [key: string]: any },
  invalidProps: string[] = INVALID_PROPS,
  shouldMerge: boolean = false,
): { [key: string]: any } => {
  if (shouldMerge) {
    invalidProps = invalidProps.concat(INVALID_PROPS);
  }

  return Object.keys(props).reduce((newProps, key) => ({
    ...newProps,
    ...(invalidProps.includes(key) ? {} : { [key]: props[key] }),
  }), {});
};
